Tienda/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tienda.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Tienda/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tienda.ServiceReference1;


namespace Tienda.Controllers
{
    public class TiendaController : Controller
    {
        Service1Client servicio = new Service1Client();
        public ActionResult Index()
        {
            return View(servicio.listado());
        }

        public ActionResult Details(string id)
        {
            if (id == null) return RedirectToAction("Index");

            Producto reg = servicio.Buscar(id);

            return View(reg);
        }
        public ActionResult Create()
        {

            ViewBag.clases = new SelectList(
                servicio.clases(), "codigo_cp", "nombre_cp");
            ViewBag.marcas = new SelectList(
                servicio.marcas(), "codigo_mp", "nombre_mp");

            return View(new Producto());

        }
        [HttpPost]
        public ActionResult Create(Producto reg,HttpPostedFileBase archivo)
        {
            ViewBag.clases = new SelectList(
               servicio.clases(), "codigo_cp", "nombre_cp", reg.Codigo_CP);
            ViewBag.marcas = new SelectList(
                servicio.marcas(), "codigo_mp", "nombre_mp", reg.Codigo_MP);

            if (!ModelState.IsValid) return View(reg);


            if (archivo == null) return View(reg);

            //guardar la foto
            archivo.SaveAs(System.IO.Path.Combine(
                    Server.MapPath("~/Fotos/"), System.IO.Path.GetFileName(archivo.FileName)));

            ViewBag.mensaje = servicio.Agregar(reg,archivo);          
            

            return View(reg);

        }
        public ActionResult Edit(string id)
        {
            if (id == null) return RedirectToAction("Index");

            Producto reg = servicio.Buscar(id);
            ViewBag.clases = new SelectList(
              servicio.clases(), "codigo_cp", "nombre_cp", reg.Codigo_CP);
            ViewBag.marcas = new SelectList(
                servicio.marcas(), "codigo_mp", "nombre_mp", reg.Codigo_MP);

            return View(reg);
        }
        [HttpPost]
        public ActionResult Edit(Producto reg, HttpPostedFileBase archivo)
        {
            ViewBag.mensaje = servicio.Editar(reg,archivo);

            ViewBag.clases = new SelectList(
              servicio.clases(), "codigo_cp", "nombre_cp", reg.Codigo_CP);
            ViewBag.marcas = new SelectList(
                servicio.marcas(), "codigo_mp", "nombre_mp", reg.Codigo_MP);

            return View(reg);
        }

    }
}

Tienda/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Tienda/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Tienda/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Tienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Tienda/Views/Tienda/Create.cshtml
@model Tienda.ServiceReference1.Producto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Tienda", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo_CP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("codigo_cp", (SelectList)ViewBag.clases)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo_MP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("codigo_mp", (SelectList)ViewBag.marcas)

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="archivo" type="file" accept="image/*" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tienda/Views/Tienda/Details.cshtml
@model Tienda.ServiceReference1.Producto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Codigo_CP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo_CP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo_MP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo_MP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio_P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stock_P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock_P)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tienda/Views/Tienda/Edit.cshtml
@model Tienda.ServiceReference1.Producto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo_CP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("codigo_cp", (SelectList)ViewBag.clases)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo_MP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("codigo_mp", (SelectList)ViewBag.marcas)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagen_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagen_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock_P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock_P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock_P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @ViewBag.mensaje
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tienda/Views/Tienda/Index.cshtml
@model IEnumerable<Tienda.ServiceReference1.Producto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codigo_CP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo_MP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagen_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio_P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stock_P)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo_CP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo_MP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Imagen_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio_P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stock_P)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Codigo_P }) |
            @Html.ActionLink("Details", "Details", new { id = item.Codigo_P }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Codigo_P })
        </td>
    </tr>
}

</table>
<div>
    @ViewBag.mensaje
</div>